### ISSUE TITLE
crash when click on update mods

### ISSUE THREAD

**Issue by Link4ever42** [JamesWilko/Payday-2-BLT#130]
Application has crashed: C++ exception
mods/base/req/ui/BLTUIControls.lua:313: attempt to call method 'IsCritical' (a nil value)

SCRIPT STACK

new() @mods/base/req/utils/UtilsClass.lua:26
_setup() @mods/base/req/ui/BLTDownloadManagerGui.lua:125
init() @mods/base/req/ui/BLTDownloadManagerGui.lua:34
new() @mods/base/req/utils/UtilsClass.lua:26
create() @mods/base/req/ui/BLTDownloadManagerGui.lua:257
set_active_components() lib/managers/menu/menucomponentmanager.lua:429
set_active_components() @mods/base/lua/MenuComponentManager.lua:19
core/lib/managers/menu/coremenulogic.lua:89
_execute_action_queue() core/lib/managers/menu/coremenulogic.lua:54
update() core/lib/managers/menu/coremenulogic.lua:64
update() core/lib/managers/menu/coremenumanager.lua:159
update() lib/managers/menumanagerpd2.lua:17
update() lib/setups/setup.lua:740
update() lib/setups/menusetup.lua:294
update() @mods/base/lua/MenuSetup.lua:6
core/lib/setups/coresetup.lua:537

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.76.327.
	CPU : Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz (1 core); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 11.0

**Comment by BangL** [comment]
this happens due to incomplete implementation if the dependencies support and will be fixed as soon this PR is merged: https://github.com/JamesWilko/Payday-2-BLT-Lua/pull/38

**Comment by UniversalAnonymousUser** [comment]
Similar context, crashes when trying to access the Download Manager.
It was working until I had a new update notification a few minutes ago ; since then it crashes everytime.


Application has crashed: C++ exception
mods/base/req/ui/BLTUIControls.lua:313: attempt to call method 'IsCritical' (a nil value)



SCRIPT STACK

new() @mods/base/req/utils/UtilsClass.lua:26
_setup() @mods/base/req/ui/BLTDownloadManagerGui.lua:125
init() @mods/base/req/ui/BLTDownloadManagerGui.lua:34
new() @mods/base/req/utils/UtilsClass.lua:26
create() @mods/base/req/ui/BLTDownloadManagerGui.lua:257
set_active_components() lib/managers/menu/menucomponentmanager.lua:429
set_active_components() @mods/base/lua/MenuComponentManager.lua:19
core/lib/managers/menu/coremenulogic.lua:89
_execute_action_queue() core/lib/managers/menu/coremenulogic.lua:54
update() core/lib/managers/menu/coremenulogic.lua:64
update() core/lib/managers/menu/coremenumanager.lua:159
update() lib/managers/menumanagerpd2.lua:17
update() lib/setups/setup.lua:740
update() lib/setups/menusetup.lua:294
update() @mods/base/lua/MenuSetup.lua:6
core/lib/setups/coresetup.lua:537


-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.76.327.
	CPU : Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 10.0 
	GPU : NVIDIA GeForce GTX 970 / nvd3dum.dll[22.21.13.8528]
	Language : @IDaadeda58d8e5a71d@
	Memory :     8159MB 136KB
	OS : 6.1.7601 (Service Pack 1) 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Realtek High Definition Audio)
