### ISSUE TITLE
Split LUA code in to a separate repository.

### ISSUE THREAD

**Issue by RomanHargrave** [JamesWilko/Payday-2-BLT#57]
As it stands there are currently _three_ BLT Loaders. One is for Windows, and two are for Linux.

* JamesWilko/Payday-2-BLT - The Original BLT, for Windows

* Ozymandias117/Payday-2-BLT (branch: linux-work) - The Original BLT, Linux Port (same old code)

* RomanHargrave/blt4l - Fresh BLT-Compatible Re-implementation (a lot of similar code), All platform code written for Linux rather than ported.

All of these support the same mods, and have the same LUA API. Since the LUA API is, for the most part, platform agnostic, it would be nice to move it to a separate repository so that anyone using it can depend on it as a submodule without pulling in the BLT loader.

This has the advantage of insuring that any BLT loader is using the same code as any other, and allowing for contributions of any BLT loader to the LUA base to benefit the rest.

**Comment by BangL** [comment]
+1
makes perfect sense to me

**Comment by JamesWilko** [comment]
Mods folder from the repo has been moved to: https://github.com/JamesWilko/Payday-2-BLT-Lua/tree/master

**Comment by RomanHargrave** [comment]
@JamesWilko great!

**Comment by BangL** [comment]
..actually the "payday2bltdll" is still a problem.
not having any solution, just saying.

**Comment by JamesWilko** [comment]
@BangL We're aware of the problem, since if we decide to push a dll update then we're going to end up with all Linux users with Windows dll's in their game folders. We'll most likely sort this out server-side so that players get the right one.
I'm also unsure if my dll "patching" method will work for Linux to begin with, since we rename a dll that is being used, and extract the new one in its place, then delete the renamed one when starting up Payday. This can be easily manually tested, but we'll also need to sort out the code to look for the different filenames based on platform (eg. `IPHLPAPI.dll` or `libblt_loader.so`).

**Comment by RomanHargrave** [comment]
@JamesWilko I haven't even thought much yet about auto-updating...

For starters, we currently ship three different binary builds. One that targets on Ubuntu Precise/SteamRT, as some users seem to have a larger shared object library provided by SteamRT, which gets in the way of other builds working, another for Ubuntu Trusty, and one for Debian Testing (simply because that's my distro).

We could easily tag the release using the preprocessor and expose it via a LUA native function, I suppose, and if a user is using a source build, we could just place a notification at the main menu.
