### ISSUE TITLE
Dev Console Suggestion

### ISSUE THREAD

**Issue by Kilandor** [JamesWilko/Payday-2-BLT#6]
I would suggest make a option to be loaded from mod.txt

This way a developer can easily switch it on/off as they want for development.

**Comment by SirWaddles** [comment]
I'm concerned how this would react to multiple mod.txt's suggesting that the console needs to be open.
The obvious solution being open it if -any- of the mods required the console, but then all it takes is a single mod developer to forget to turn it off when they release an update and then everyone's got consoles opening up.

The reason we didn't do something like this out of the bat, is because we wanted to maintain as much lua interoperability as possible, so I forwarded the opening/closing of the developer console as a lua function. This may have been a mistake, as there are many things that can happen and need to be loggable between when the game starts up and when the lua state is initiated, our hack solution was for the opening of the console to be the first thing that happens as soon as the lua state comes up. (hence the if true statement in base.lua)

I'm open to alternative suggestions that solve these problems.

**Comment by Kilandor** [comment]
The only other suggestion I can think of is a config file in the root of mods or elsewhere, that is outside of a developers folder and outside of mod.txt

This file could contain optional configs for developers. This would prevent any problems of a developer including it or leaving it on by mistake. This also prevents the problem of dealing with any multiple sources of configuration as this would come from once source.

**Comment by NotAdam** [comment]
Just have a developer config file which allows certain settings to be set and if the file doesn't exist it's ignored. Anyone who cares will create the file and set the relevant settings, everyone else won't know about it's existence.

**Comment by gir489** [comment]
This is stupid, since this leaves debug/testing configuration in the deployable (mod.txt) instead of the developer's BLT base folder, which should be excluded from the production environment. If the developer wants it, they can change that if false then condition in base.lua. I find it extreemly unhelpful and annoying, since [glogg](http://glogg.bonnefon.org/) can read the running load for the day in a nice neat searchable and copyable format. The console is a relic from the days of terminals and it needs to go away and never come back. Fuck terminals, fuck the console and fuck Linux. GUIS are the future.

**Comment by JamesWilko** [comment]
Console is now loaded by placing developer.txt into the mods folder.
