### ISSUE TITLE
FATAL ERROR: mods/base/req/json-1.0.lua:212: Failed to scan constant from string {... [r14]

### ISSUE THREAD

**Issue by AmperAndSand** [JamesWilko/Payday-2-BLT#67]
Console and log file is getting filled with 
```
FATAL ERROR: mods/base/req/json-1.0.lua:212: Failed to scan constant from string {... 
Lua: Found a json error, attempting to use old json loader!
```

...error messages for every mod installed. This issue was not present in the version prior to r14. The mods still work, but the console and log file is getting filled with the error messages and json file contents of every mod installed.

Sample log file with the above-mentioned issue:
[2017_04_29_log.txt](https://github.com/JamesWilko/Payday-2-BLT/files/965962/2017_04_29_log.txt)

**Comment by BangL** [comment]
thats because the latest update uses a new json parser, which is more strict than the old one.. it's not an error of the blt, it just shows errors of the mod which got ignored before.

example:
`02:41:41 PM FATAL ERROR: mods/base/req/json-1.0.lua:212: Failed to scan constant from string {
    "name" : "PocoHud3",
    "description" : "Payday 2 Interface Enhancer Mod",
    "author" : "zenyr",
    "contact" : "zenyr(at)zenyr.com",
    "version" : "v0.35 (r467)",
    "priority" : 4,
    "updates" : [
        {
            "revision" : 11,
            "identifier" : "pocohud3",
        }
    ],
    "persist_scripts" : [
        { "global" : "UNDERSCORE", "script_path" : "poco/common.lua" },
        { "global" : "PocoHud3", "script_path" : "poco/Hud3.lua" }
    ]
}
 at starting position 250`

in this case there is a comma after `"identifier" : "pocohud3"`, which is invalid in json.

**Comment by BangL** [comment]
here is a nice to to validate json code online:
https://jsonlint.com/

**Comment by JamesWilko** [comment]
Correct, the new update forces mods to use stricter, valid json. If it files parsing using the updated json parser then the BLT will automatically revert back to the old parser to ensure that the mod still loads and works. The mod author needs to update their mod to use valid json instead.
