### ISSUE TITLE
FATAL ERROR: mods/base/req/json-1.0.lua:212: Failed to scan constant from string

### ISSUE THREAD

**Issue by HetNeSS** [JamesWilko/Payday-2-BLT#71]
After some time playing, Payday crashes with a lot of kind of the same errors, with all mods are writed on the logs. At the start of the log file there is something about a hud being installed, but I don't think it's a reason. It did crash each time even when that "fed.inventory" was installed, and the hud is actually works fine, with that "federal inventory" mod or without it. Can't attach the log file for some weird reason, so just putting it up onto another source.
https://www.dropbox.com/s/m1q5e3wwvad0rzy/2017_06_16_log.txt?dl=0
BLT version is 1.08
P.S. It's kinda lagging while trying to check updates, like, to wait for a half of a minute on the main menu screen, untill the notification about updates will pop up, and even if you try to click on the "update", it will load 0kb of 0kb total, and it's not updating at all, and.. I've just leave it here be, if anyone know the reason, it would be greatly appreciated

**Comment by HetNeSS** [comment]
Like, when it finally checks the updates available and prints a list of it ( https://www.dropbox.com/s/zl4v52d2n7qx8rb/20170616221346_1.jpg?dl=0 ), if you try to click on any of the "update" each mod request, mostly of the time it's just nothing happens. https://www.dropbox.com/s/4h3c8bwmrre811v/123.txt?dl=0

**Comment by JamesWilko** [comment]
Your mod files are using non-standard JSON, you need to tell the mod authors to fix it if you want to remove the error. The mods are loaded using the original JSON parser if the new one fails so that the mods will still work.

Slow updates are due to the PaydayMods site being hit hard by tons of new users, it will be slow for  a while until the new users bleed off over time.
