### ISSUE TITLE
Updating BLT DLL from the BLT menu renames IPHLPAPI.dll to IPHLPAPI_temp.dll

### ISSUE THREAD

**Issue by 47Haven** [JamesWilko/Payday-2-BLT#77]
However the game keeps asking me to update it, yet when i update the game clicking on "Update Payday 2 BLT DLL", it simply just rename the IPHLPAPI.dll

Was this a false alarm?

**Comment by SirWaddles** [comment]
[This is how it updates the DLL](https://github.com/JamesWilko/Payday-2-BLT-Lua/blob/master/mods/base/req/update_mods.lua#L304) when there's a new version for that (which is actually quite rare)

Likely, something went wrong, whether it be access levels or in-use process. You might want to download the latest version and install it manually.

**Comment by rnorris7756** [comment]
I noticed this as well.  After allowing this update, the SHA-1 sum of both IPHLPAPI.dll and  IPHLPAPI_temp.dll are the same as IPHLPAPI.dll before the update.

```
$ sha1sum.exe IPHLPAPI.dll
3faf8f7d65c336da5ae5de3f56ded9ea674b1be0 *IPHLPAPI.dll

$ sha1sum.exe IPHLPAPI_temp.dll
3faf8f7d65c336da5ae5de3f56ded9ea674b1be0 *IPHLPAPI_temp.dll
```

Downloading the latest version and installing manually notifies the user of this update, but it doesn't appear to be harmful, since it doesn't change the installed DLL.

**Comment by JamesWilko** [comment]
DLL updating has been removed from the BLT, so this is now a non-issue.
