### ISSUE TITLE
BLT DOESNT WORK AFTER UPDATE 153

### ISSUE THREAD

**Issue by RapidCrocodile** [JamesWilko/Payday-2-BLT#86]
BLT doesn't show up at all when I install it in update 153

**Comment by Luffyyy** [comment]
Update manually

**Comment by RapidCrocodile** [comment]
I've installed the top file and it doesn't show up still

**Comment by xtakku** [comment]
I have also updated manually and it doesn't show anything ingame. I got rid of all mods and mod_overrides and yet nothing happens anywhere ingame. I know for a fact I did everything right because BLT is actually writing to the log.txt, spamming this message quite frequently:
Game is launching fine for me, but I don't see the mod manager ingame at all. I'd almost think BLT wasn't installed, but it definitely is, and it even writes to the logfile. This message pops up repeatedly:
(..\src\InitiateState.cpp:671) mods/base/req/BLTModManager.lua:208: bad argument #1 to 'pairs' (table expected, got nil)

**Comment by AmperAndSand** [comment]
Same issue here. Removed the entire 'mods' folder (including `mods/saves/` within it) and IPHLAPI.dll. Then installed latest release from https://github.com/JamesWilko/Payday-2-BLT/releases. The game does not start at all. Task Manager says payday2_win32_release.exe is currently running but the game does not open up.
